/**
 * Daily/weekly collector runner.
 * Fetches monitored sources, hashes content, records scrape_runs,
 * and writes alerts when content changes.
 *
 * Does NOT auto-overwrite curated matrix/gap data (proposal mode).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  openDb,
  migrate,
  listEnabledSources,
  updateSourceCheck,
  insertScrapeRun,
  insertEvent,
} from "@fft/db";
import { collectorEventId, hashContent } from "./core.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "../../..");
const alertsDir = path.join(repoRoot, "reports", "alerts");
const cacheDir = path.join(repoRoot, "data", "cache");

const USER_AGENT =
  "FrontierFeatureTracker/0.1 (+internal competitive intelligence; respectful crawl)";

async function fetchSource(
  url: string,
): Promise<{ ok: boolean; body: string; status: number; error?: string }> {
  try {
    const res = await fetch(url, {
      headers: {
        "User-Agent": USER_AGENT,
        Accept: "text/html,application/xhtml+xml,*/*",
      },
      redirect: "follow",
      signal: AbortSignal.timeout(30_000),
    });
    const body = await res.text();
    return {
      ok: res.ok,
      body,
      status: res.status,
      error: res.ok ? undefined : `HTTP ${res.status}`,
    };
  } catch (e) {
    return {
      ok: false,
      body: "",
      status: 0,
      error: e instanceof Error ? e.message : String(e),
    };
  }
}

function writeAlert(date: string, lines: string[]) {
  if (lines.length === 0) return;
  fs.mkdirSync(alertsDir, { recursive: true });
  const file = path.join(alertsDir, `${date}.md`);
  const header = `# Alerts — ${date}\n\nGenerated by collectors.\n\n`;
  const existing = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : header;
  const block = lines.map((l) => `- ${l}`).join("\n") + "\n";
  fs.writeFileSync(
    file,
    existing.endsWith("\n\n") || existing === header ? existing + block : existing + "\n" + block,
  );
}

async function main() {
  const { sqlite } = openDb();
  migrate(sqlite);
  fs.mkdirSync(cacheDir, { recursive: true });

  const allSources = listEnabledSources(sqlite);
  const today = new Date().toISOString().slice(0, 10);
  const alertLines: string[] = [];
  let changes = 0;
  let failures = 0;

  console.log(`Collecting ${allSources.length} sources…`);

  for (const source of allSources) {
    const startedAt = new Date().toISOString();
    const result = await fetchSource(source.url);
    const finishedAt = new Date().toISOString();

    if (!result.ok) {
      failures++;
      insertScrapeRun(sqlite, {
        sourceId: source.id,
        startedAt,
        finishedAt,
        status: "error",
        changeDetected: false,
        error: result.error ?? "unknown",
      });
      updateSourceCheck(sqlite, source.id, {
        lastCheckedAt: finishedAt,
        lastStatus: "error",
      });
      console.log(`  ✗ ${source.name}: ${result.error}`);
      await new Promise((r) => setTimeout(r, 500));
      continue;
    }

    const contentHash = hashContent(result.body);
    const changeDetected = Boolean(source.lastHash && source.lastHash !== contentHash);
    const isFirst = !source.lastHash;

    insertScrapeRun(sqlite, {
      sourceId: source.id,
      startedAt,
      finishedAt,
      status: "ok",
      changeDetected,
      contentHash,
    });

    updateSourceCheck(sqlite, source.id, {
      lastCheckedAt: finishedAt,
      lastHash: contentHash,
      lastStatus: "ok",
    });

    const cachePath = path.join(cacheDir, `${source.id}.html`);
    fs.writeFileSync(cachePath, result.body.slice(0, 500_000));

    if (changeDetected) {
      changes++;
      alertLines.push(`Change detected: **${source.name}** (${source.url})`);
      console.log(`  Δ ${source.name}`);

      insertEvent(sqlite, {
        id: collectorEventId(source.id),
        eventType: "other",
        companyId: source.companyId,
        title: `Source change: ${source.name}`,
        summary: `Collector detected content hash change on ${source.url}. Review for model/product/pricing updates (proposal mode — does not auto-edit matrix).`,
        occurredAt: finishedAt.slice(0, 10),
        sourceUrl: source.url,
        severity: source.sourceType === "ir" ? "notable" : "info",
        tags: ["scrape", "change-detection", source.sourceType],
      });
    } else {
      console.log(`  · ${source.name}${isFirst ? " (baseline hash stored)" : ""}`);
    }

    await new Promise((r) => setTimeout(r, 500));
  }

  writeAlert(today, alertLines);

  const webhook = process.env.FFT_WEBHOOK_URL;
  if (webhook && alertLines.length > 0) {
    try {
      await fetch(webhook, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          text: `Frontier Feature Tracker: ${changes} source change(s) on ${today}`,
          changes: alertLines,
        }),
      });
    } catch (e) {
      console.warn("Webhook failed:", e);
    }
  }

  sqlite.close();
  console.log(`\nDone. changes=${changes} failures=${failures}`);
  if (alertLines.length) {
    console.log(`Alerts written to reports/alerts/${today}.md`);
  }
  if (failures > 0) process.exitCode = 1;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
